### DISCUSSION TITLE
How to bind `Super + r` to run cmd mode directly like `rofi -show run`?

### DISCUSSION THREAD

**Discussion by TD-Sky** [mdgaziur/findex#41] [Q&A] [answered]
I think it more convenient than writing the prefix manually.

**Comment by mdgaziur** [comment]
Ahh that's a nice suggestion. I think an option for triggering plugins thru shortcuts can be added. Putting it into my to-do list.

**Comment by mdgaziur** [comment]
Update: added this feature. To try this, add custom keyboard shortcut for plugin, run Findex and press the shortcut keys. Findex will automatically insert the prefix of the plugin into the search bar. I guess this is what you wanted?

**Reply by TD-Sky** [reply]
The config in `settings.toml` doesn't work:

```toml
[plugins.cmd]
prefix = "cmd!"
keyboard_shortcut = "<Super>r"
path = "~/.config/findex/plugins/libcmd.so"
config = {}
```

My version is `development:6ad4468`.

The `<Super>r` isn't be occupied.
